### PR TITLE
Pkg.add("Church")

### PR DESCRIPTION
**Pull request by WestleyArgentum**

### CODE REVIEW

**Comment by LaurenceA** [comment]
Good point.  However, I don't have an official version yet, so you need to use Pkg.clone("Church")?

**Comment by WestleyArgentum** [comment]
Pkg.clone("https://github.com/LaurenceA/Church.jl.git")

**Comment by LaurenceA** [comment]
I've registered it, just not put up a tagged version.  Pkg.clone("Church")
seems to work for me?  Does it work for you?

**Comment by WestleyArgentum** [comment]
I could be doing something wrong, but after a `Pkg.update()` I get:

```
julia> Pkg.clone("Church")
ERROR: can't determine package name from URL: Church
 in clone at pkg/entry.jl:147
 in anonymous at pkg/dir.jl:25
 in cd at file.jl:22
 in cd at pkg/dir.jl:25
 in clone at pkg.jl:29
```

Which is why I posted with the whole path... but it seems like, since it's registered, `Pkg.clone("Church")` should work

**Comment by WestleyArgentum** [comment]
Ah, no, my metadata origin was screwed up, your version works

**Pull request closed without merging**
